services:
  ditto:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_AUTHORIZED_USER=${POSTGRES_AUTHORIZED_USER}
      - POSTGRES_USER_PASSWORD=${POSTGRES_USER_PASSWORD}
    expose:
      - "7100"
    ports: 
      - "7100:7100"
  # Set Up Postgres Image